// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

//Customers
export const GET_CUSTOMER_DETAIL_REQUEST = 'GET_CUSTOMER_DETAIL_REQUEST'
export const GET_CUSTOMER_DETAIL_SUCCESS = 'GET_CUSTOMER_DETAIL_SUCCESS'
export const GET_CUSTOMER_DETAIL_FAILED = 'GET_CUSTOMER_DETAIL_FAILED'

export const GET_CUSTOMERBYID_DETAIL_REQUEST = 'GET_CUSTOMERBYID_DETAIL_REQUEST'
export const GET_CUSTOMERBYID_DETAIL_SUCCESS = 'GET_CUSTOMERBYID_DETAIL_SUCCESS'
export const GET_CUSTOMERBYID_DETAIL_FAILED = 'GET_CUSTOMERBYID_DETAIL_FAILED'

export const UPDATE_CUSTOMER_DETAIL_REQUEST = 'UPDATE_CUSTOMER_DETAIL_REQUEST'
export const UPDATE_CUSTOMER_DETAIL_SUCCESS = 'UPDATE_CUSTOMER_DETAIL_SUCCESS'
export const UPDATE_CUSTOMER_DETAIL_FAILED = 'UPDATE_CUSTOMER_DETAIL_FAILED'

export const ADD_NEW_CUSTOMER_DETAIL_REQUEST = 'ADD_NEW_CUSTOMER_DETAIL_REQUEST'
export const ADD_NEW_CUSTOMER_DETAIL_SUCCESS = 'ADD_NEW_CUSTOMER_DETAIL_SUCCESS'
export const ADD_NEW_CUSTOMER_DETAIL_FAILED = 'ADD_NEW_CUSTOMER_DETAIL_FAILED'

export const DELETE_CUSTOMER_DETAIL_REQUEST = 'DELETE_CUSTOMER_DETAIL_REQUEST'
export const DELETE_CUSTOMER_DETAIL_SUCCESS = 'DELETE_CUSTOMER_DETAIL_SUCCESS'
export const DELETE_CUSTOMER_DETAIL_FAILED = 'DELETE_CUSTOMER_DETAIL_FAILED'

//Pick up History
export const GET_PICKUPHISTORY_DETAIL_REQUEST = 'GET_PICKUPHISTORY_DETAIL_REQUEST'
export const GET_PICKUPHISTORY_DETAIL_SUCCESS = 'GET_PICKUPHISTORY_DETAIL_SUCCESS'
export const GET_PICKUPHISTORY_DETAIL_FAILED = 'GET_PICKUPHISTORY_DETAIL_FAILED'

//Collectors
export const GET_COLLECTOR_DETAIL_REQUEST = 'GET_COLLECTOR_DETAIL_REQUEST'
export const GET_COLLECTOR_DETAIL_SUCCESS = 'GET_COLLECTOR_DETAIL_SUCCESS'
export const GET_COLLECTOR_DETAIL_FAILED = 'GET_COLLECTOR_DETAIL_FAILED'

export const GET_COLLECTORBYID_DETAIL_REQUEST = 'GET_COLLECTORBYID_DETAIL_REQUEST'
export const GET_COLLECTORBYID_DETAIL_SUCCESS = 'GET_COLLECTORBYID_DETAIL_SUCCESS'
export const GET_COLLECTORBYID_DETAIL_FAILED = 'GET_COLLECTORBYID_DETAIL_FAILED'

export const ADD_NEW_COLLECTOR_DETAIL_REQUEST = 'ADD_NEW_COLLECTOR_DETAIL_REQUEST'
export const ADD_NEW_COLLECTOR_DETAIL_SUCCESS = 'ADD_NEW_COLLECTOR_DETAIL_SUCCESS'
export const ADD_NEW_COLLECTOR_DETAIL_FAILED = 'ADD_NEW_COLLECTOR_DETAIL_FAILED'

export const UPDATE_COLLECTOR_DETAIL_REQUEST = 'UPDATE_COLLECTOR_DETAIL_REQUEST'
export const UPDATE_COLLECTOR_DETAIL_SUCCESS = 'UPDATE_COLLECTOR_DETAIL_SUCCESS'
export const UPDATE_COLLECTOR_DETAIL_FAILED = 'UPDATE_COLLECTOR_DETAIL_FAILED'

export const DELETE_COLLECTOR_DETAIL_REQUEST = 'DELETE_COLLECTOR_DETAIL_REQUEST'
export const DELETE_COLLECTOR_DETAIL_SUCCESS = 'DELETE_COLLECTOR_DETAIL_SUCCESS'
export const DELETE_COLLECTOR_DETAIL_FAILED = 'DELETE_COLLECTOR_DETAIL_FAILED'

//Collector History
export const GET_COLLECTORHISTORY_DETAIL_REQUEST = 'GET_COLLECTORHISTORY_DETAIL_REQUEST'
export const GET_COLLECTORHISTORY_DETAIL_SUCCESS = 'GET_COLLECTORHISTORY_DETAIL_SUCCESS'
export const GET_COLLECTORHISTORY_DETAIL_FAILED = 'GET_COLLECTORHISTORY_DETAIL_FAILED'

//Routes
export const GET_ROUTES_DETAIL_REQUEST = 'GET_ROUTES_DETAIL_REQUEST'
export const GET_ROUTES_DETAIL_SUCCESS = 'GET_ROUTES_DETAIL_SUCCESS'
export const GET_ROUTES_DETAIL_FAILED = 'GET_ROUTES_DETAIL_FAILED'

export const GET_ROUTESBYID_DETAIL_REQUEST = 'GET_ROUTESBYID_DETAIL_REQUEST'
export const GET_ROUTESBYID_DETAIL_SUCCESS = 'GET_ROUTESBYID_DETAIL_SUCCESS'
export const GET_ROUTESBYID_DETAIL_FAILED = 'GET_ROUTESBYID_DETAIL_FAILED'

export const ADD_ROUTES_DETAIL_REQUEST = 'ADD_ROUTES_DETAIL_REQUEST'
export const ADD_ROUTES_DETAIL_SUCCESS = 'ADD_ROUTES_DETAIL_SUCCESS'
export const ADD_ROUTES_DETAIL_FAILED = 'ADD_ROUTES_DETAIL_FAILED'

export const UPDATE_ROUTES_DETAIL_REQUEST = 'UPDATE_ROUTES_DETAIL_REQUEST'
export const UPDATE_ROUTES_DETAIL_SUCCESS = 'UPDATE_ROUTES_DETAIL_SUCCESS'
export const UPDATE_ROUTES_DETAIL_FAILED = 'UPDATE_ROUTES_DETAIL_FAILED'

export const DELETE_ROUTES_DETAIL_REQUEST = 'DELETE_ROUTES_DETAIL_REQUEST'
export const DELETE_ROUTES_DETAIL_SUCCESS = 'DELETE_ROUTES_DETAIL_SUCCESS'
export const DELETE_ROUTES_DETAIL_FAILED = 'DELETE_ROUTES_DETAIL_FAILED'

//Devices
export const GET_DEVICES_DETAIL_REQUEST = 'GET_DEVICES_DETAIL_REQUEST'
export const GET_DEVICES_DETAIL_SUCCESS = 'GET_DEVICES_DETAIL_SUCCESS'
export const GET_DEVICES_DETAIL_FAILED = 'GET_DEVICES_DETAIL_FAILED'

export const GET_DEVICESBYID_DETAIL_REQUEST = 'GET_DEVICESBYID_DETAIL_REQUEST'
export const GET_DEVICESBYID_DETAIL_SUCCESS = 'GET_DEVICESBYID_DETAIL_SUCCESS'
export const GET_DEVICESBYID_DETAIL_FAILED = 'GET_DEVICESBYID_DETAIL_FAILED'

export const ADD_DEVICES_DETAIL_REQUEST = 'ADD_DEVICES_DETAIL_REQUEST'
export const ADD_DEVICES_DETAIL_SUCCESS = 'ADD_DEVICES_DETAIL_SUCCESS'
export const ADD_DEVICES_DETAIL_FAILED = 'ADD_DEVICES_DETAIL_FAILED'

export const UPDATE_DEVICES_DETAIL_REQUEST = 'UPDATE_DEVICES_DETAIL_REQUEST'
export const UPDATE_DEVICES_DETAIL_SUCCESS = 'UPDATE_DEVICES_DETAIL_SUCCESS'
export const UPDATE_DEVICES_DETAIL_FAILED = 'UPDATE_DEVICES_DETAIL_FAILED'

export const DELETE_DEVICES_DETAIL_REQUEST = 'DELETE_DEVICES_DETAIL_REQUEST'
export const DELETE_DEVICES_DETAIL_SUCCESS = 'DELETE_DEVICES_DETAIL_SUCCESS'
export const DELETE_DEVICES_DETAIL_FAILED = 'DELETE_DEVICES_DETAIL_FAILED'

//Barcode
export const GET_BARCODE_DETAIL_REQUEST = 'GET_BARCODE_DETAIL_REQUEST'
export const GET_BARCODE_DETAIL_SUCCESS = 'GET_BARCODE_DETAIL_SUCCESS'
export const GET_BARCODE_DETAIL_FAILED = 'GET_BARCODE_DETAIL_FAILED'

export const GET_BARCODEBYID_DETAIL_REQUEST = 'GET_BARCODEBYID_DETAIL_REQUEST'
export const GET_BARCODEBYID_DETAIL_SUCCESS = 'GET_BARCODEBYID_DETAIL_SUCCESS'
export const GET_BARCODEBYID_DETAIL_FAILED = 'GET_BARCODEBYID_DETAIL_FAILED'

export const ADD_BARCODE_DETAIL_REQUEST = 'ADD_BARCODE_DETAIL_REQUEST'
export const ADD_BARCODE_DETAIL_SUCCESS = 'ADD_BARCODE_DETAIL_SUCCESS'
export const ADD_BARCODE_DETAIL_FAILED = 'ADD_BARCODE_DETAIL_FAILED'

export const UPDATE_BARCODE_DETAIL_REQUEST = 'UPDATE_BARCODE_DETAIL_REQUEST'
export const UPDATE_BARCODE_DETAIL_SUCCESS = 'UPDATE_BARCODE_DETAIL_SUCCESS'
export const UPDATE_BARCODE_DETAIL_FAILED = 'UPDATE_BARCODE_DETAIL_FAILED'

export const DELETE_BARCODE_DETAIL_REQUEST = 'DELETE_BARCODE_DETAIL_REQUEST'
export const DELETE_BARCODE_DETAIL_SUCCESS = 'DELETE_BARCODE_DETAIL_SUCCESS'
export const DELETE_BARCODE_DETAIL_FAILED = 'DELETE_BARCODE_DETAIL_FAILED'

//Barcode Detail
export const GET_BARCODE_BYID_DETAIL_REQUEST = 'GET_BARCODE_BYID_DETAIL_REQUEST'
export const GET_BARCODE_BYID_DETAIL_SUCCESS = 'GET_BARCODE_BYID_DETAIL_SUCCESS'
export const GET_BARCODE_BYID_DETAIL_FAILED = 'GET_BARCODE_BYID_DETAIL_FAILED'

//Customer-Barcode
export const GET_CUSTOMERBARCODE_DETAIL_REQUEST = 'GET_CUSTOMERBARCODE_DETAIL_REQUEST'
export const GET_CUSTOMERBARCODE_DETAIL_SUCCESS = 'GET_CUSTOMERBARCODE_DETAIL_SUCCESS'
export const GET_CUSTOMERBARCODE_DETAIL_FAILED = 'GET_CUSTOMERBARCODE_DETAIL_FAILED'

//Payments
export const GET_PAYMENTS_DETAIL_REQUEST = 'GET_PAYMENTS_DETAIL_REQUEST'
export const GET_PAYMENTS_DETAIL_SUCCESS = 'GET_PAYMENTS_DETAIL_SUCCESS'
export const GET_PAYMENTS_DETAIL_FAILED = 'GET_PAYMENTS_DETAIL_FAILED'

export const GET_PAYMENTS_BYID_DETAIL_REQUEST = 'GET_PAYMENTS_BYID_DETAIL_REQUEST'
export const GET_PAYMENTS_BYID_DETAIL_SUCCESS = 'GET_PAYMENTS_BYID_DETAIL_SUCCESS'
export const GET_PAYMENTS_BYID_DETAIL_FAILED = 'GET_PAYMENTS_BYID_DETAIL_FAILED'

export const ADD_PAYMENTS_DETAIL_REQUEST = 'ADD_PAYMENTS_DETAIL_REQUEST'
export const ADD_PAYMENTS_DETAIL_SUCCESS = 'ADD_PAYMENTS_DETAIL_SUCCESS'
export const ADD_PAYMENTS_DETAIL_FAILED = 'ADD_PAYMENTS_DETAIL_FAILED'

export const UPDATE_PAYMENTS_DETAIL_REQUEST = 'UPDATE_PAYMENTS_DETAIL_REQUEST'
export const UPDATE_PAYMENTS_DETAIL_SUCCESS = 'UPDATE_PAYMENTS_DETAIL_SUCCESS'
export const UPDATE_PAYMENTS_DETAIL_FAILED = 'UPDATE_PAYMENTS_DETAIL_FAILED'

export const DELETE_PAYMENTS_DETAIL_REQUEST = 'DELETE_PAYMENTS_DETAIL_REQUEST'
export const DELETE_PAYMENTS_DETAIL_SUCCESS = 'DELETE_PAYMENTS_DETAIL_SUCCESS'
export const DELETE_PAYMENTS_DETAIL_FAILED = 'DELETE_PAYMENTS_DETAIL_FAILED'

//Transactions
export const GET_TRANSACTIONS_DETAIL_REQUEST = 'GET_TRANSACTIONS_DETAIL_REQUEST'
export const GET_TRANSACTIONS_DETAIL_SUCCESS = 'GET_TRANSACTIONS_DETAIL_SUCCESS'
export const GET_TRANSACTIONS_DETAIL_FAILED = 'GET_TRANSACTIONS_DETAIL_FAILED'

export const GET_TRANSACTIONSBYID_DETAIL_REQUEST = 'GET_TRANSACTIONSBYID_DETAIL_REQUEST'
export const GET_TRANSACTIONSBYID_DETAIL_SUCCESS = 'GET_TRANSACTIONSBYID_DETAIL_SUCCESS'
export const GET_TRANSACTIONSBYID_DETAIL_FAILED = 'GET_TRANSACTIONSBYID_DETAIL_FAILED'

export const ADD_NEW_TRANSACTIONS_DETAIL_REQUEST = 'ADD_NEW_TRANSACTIONS_DETAIL_REQUEST'
export const ADD_NEW_TRANSACTIONS_DETAIL_SUCCESS = 'ADD_NEW_TRANSACTIONS_DETAIL_SUCCESS'
export const ADD_NEW_TRANSACTIONS_DETAIL_FAILED = 'ADD_NEW_TRANSACTIONS_DETAIL_FAILED'

export const UPDATE_TRANSACTIONS_DETAIL_REQUEST = 'UPDATE_TRANSACTIONS_DETAIL_REQUEST'
export const UPDATE_TRANSACTIONS_DETAIL_SUCCESS = 'UPDATE_TRANSACTIONS_DETAIL_SUCCESS'
export const UPDATE_TRANSACTIONS_DETAIL_FAILED = 'UPDATE_TRANSACTIONS_DETAIL_FAILED'

export const DELETE_TRANSACTIONS_DETAIL_REQUEST = 'DELETE_TRANSACTIONS_DETAIL_REQUEST'
export const DELETE_TRANSACTIONS_DETAIL_SUCCESS = 'DELETE_TRANSACTIONS_DETAIL_SUCCESS'
export const DELETE_TRANSACTIONS_DETAIL_FAILED = 'DELETE_TRANSACTIONS_DETAIL_FAILED'

//Transactions by Customer
export const GET_TRANSACTIONS_BYCUSTOMER_DETAIL_REQUEST = 'GET_TRANSACTIONS_BYCUSTOMER_DETAIL_REQUEST'
export const GET_TRANSACTIONS_BYCUSTOMER_DETAIL_SUCCESS = 'GET_TRANSACTIONS_BYCUSTOMER_DETAIL_SUCCESS'
export const GET_TRANSACTIONS_BYCUSTOMER_DETAIL_FAILED = 'GET_TRANSACTIONS_BYCUSTOMER_DETAIL_FAILED'

//Service-Requests
export const GET_SERVICEREQUESTS_DETAIL_REQUEST = 'GET_SERVICEREQUESTS_DETAIL_REQUEST'
export const GET_SERVICEREQUESTS_DETAIL_SUCCESS = 'GET_SERVICEREQUESTS_DETAIL_SUCCESS'
export const GET_SERVICEREQUESTS_DETAIL_FAILED = 'GET_SERVICEREQUESTS_DETAIL_FAILED'

export const GET_SERVICEREQUESTSBYID_DETAIL_REQUEST = 'GET_SERVICEREQUESTSBYID_DETAIL_REQUEST'
export const GET_SERVICEREQUESTSBYID_DETAIL_SUCCESS = 'GET_SERVICEREQUESTSBYID_DETAIL_SUCCESS'
export const GET_SERVICEREQUESTSBYID_DETAIL_FAILED = 'GET_SERVICEREQUESTSBYID_DETAIL_FAILED'

export const ADD_NEW_SERVICEREQUESTS_DETAIL_REQUEST = 'ADD_NEW_SERVICEREQUESTS_DETAIL_REQUEST'
export const ADD_NEW_SERVICEREQUESTS_DETAIL_SUCCESS = 'ADD_NEW_SERVICEREQUESTS_DETAIL_SUCCESS'
export const ADD_NEW_SERVICEREQUESTS_DETAIL_FAILED = 'ADD_NEW_SERVICEREQUESTS_DETAIL_FAILED'

export const UPDATE_SERVICEREQUESTS_DETAIL_REQUEST = 'UPDATE_SERVICEREQUESTS_DETAIL_REQUEST'
export const UPDATE_SERVICEREQUESTS_DETAIL_SUCCESS = 'UPDATE_SERVICEREQUESTS_DETAIL_SUCCESS'
export const UPDATE_SERVICEREQUESTS_DETAIL_FAILED = 'UPDATE_SERVICEREQUESTS_DETAIL_FAILED'

export const DELETE_SERVICEREQUESTS_DETAIL_REQUEST = 'DELETE_SERVICEREQUESTS_DETAIL_REQUEST'
export const DELETE_SERVICEREQUESTS_DETAIL_SUCCESS = 'DELETE_SERVICEREQUESTS_DETAIL_SUCCESS'
export const DELETE_SERVICEREQUESTS_DETAIL_FAILED = 'DELETE_SERVICEREQUESTS_DETAIL_FAILED'

export const CLOSE_SERVICEREQUESTS_DETAIL_REQUEST = 'CLOSE_SERVICEREQUESTS_DETAIL_REQUEST'
export const CLOSE_SERVICEREQUESTS_DETAIL_SUCCESS = 'CLOSE_SERVICEREQUESTS_DETAIL_SUCCESS'
export const CLOSE_SERVICEREQUESTS_DETAIL_FAILED = 'CLOSE_SERVICEREQUESTS_DETAIL_FAILED'

//Notes
export const GET_NOTESLIST_DETAIL_REQUEST = 'GET_NOTESLIST_DETAIL_REQUEST'
export const GET_NOTESLIST_DETAIL_SUCCESS = 'GET_NOTESLIST_DETAIL_SUCCESS'
export const GET_NOTESLIST_DETAIL_FAILED = 'GET_NOTESLIST_DETAIL_FAILED'

export const GET_NOTESLISTBYID_DETAIL_REQUEST = 'GET_NOTESLISTBYID_DETAIL_REQUEST'
export const GET_NOTESLISTBYID_DETAIL_SUCCESS = 'GET_NOTESLISTBYID_DETAIL_SUCCESS'
export const GET_NOTESLISTBYID_DETAIL_FAILED = 'GET_NOTESLISTBYID_DETAIL_FAILED'

export const ADD_NEW_NOTES_DETAIL_REQUEST = 'ADD_NEW_NOTES_DETAIL_REQUEST'
export const ADD_NEW_NOTES_DETAIL_SUCCESS = 'ADD_NEW_NOTES_DETAIL_SUCCESS'
export const ADD_NEW_NOTES_DETAIL_FAILED = 'ADD_NEW_NOTES_DETAIL_FAILED'

export const UPDATE_NOTES_DETAIL_REQUEST = 'UPDATE_NOTES_DETAIL_REQUEST'
export const UPDATE_NOTES_DETAIL_SUCCESS = 'UPDATE_NOTES_DETAIL_SUCCESS'
export const UPDATE_NOTES_DETAIL_FAILED = 'UPDATE_NOTES_DETAIL_FAILED'

export const DELETE_NEW_NOTES_DETAIL_REQUEST = 'DELETE_NEW_NOTES_DETAIL_REQUEST'
export const DELETE_NEW_NOTES_DETAIL_SUCCESS = 'DELETE_NEW_NOTES_DETAIL_SUCCESS'
export const DELETE_NEW_NOTES_DETAIL_FAILED = 'DELETE_NEW_NOTES_DETAIL_FAILED'

//Users
export const GET_USERS_DETAIL_REQUEST = 'GET_USERS_DETAIL_REQUEST'
export const GET_USERS_DETAIL_SUCCESS = 'GET_USERS_DETAIL_SUCCESS'
export const GET_USERS_DETAIL_FAILED = 'GET_USERS_DETAIL_FAILED'

export const ADD_USERS_DETAIL_REQUEST = 'ADD_USERS_DETAIL_REQUEST'
export const ADD_USERS_DETAIL_SUCCESS = 'ADD_USERS_DETAIL_SUCCESS'
export const ADD_USERS_DETAIL_FAILED = 'ADD_USERS_DETAIL_FAILED'

export const UPDATE_USERS_DETAIL_REQUEST = 'UPDATE_USERS_DETAIL_REQUEST'
export const UPDATE_USERS_DETAIL_SUCCESS = 'UPDATE_USERS_DETAIL_SUCCESS'
export const UPDATE_USERS_DETAIL_FAILED = 'UPDATE_USERS_DETAIL_FAILED'

export const DELETE_USERS_DETAIL_REQUEST = 'DELETE_USERS_DETAIL_REQUEST'
export const DELETE_USERS_DETAIL_SUCCESS = 'DELETE_USERS_DETAIL_SUCCESS'
export const DELETE_USERS_DETAIL_FAILED = 'DELETE_USERS_DETAIL_FAILED'

//updatepass
export const UPDATE_USERSPASS_DETAIL_REQUEST = 'UPDATE_USERSPASS_DETAIL_REQUEST'
export const UPDATE_USERSPASS_DETAIL_SUCCESS = 'UPDATE_USERSPASS_DETAIL_SUCCESS'
export const UPDATE_USERSPASS_DETAIL_FAILED = 'UPDATE_USERSPASS_DETAIL_FAILED'

//Userbyid
export const GET_USERSBYID_DETAIL_REQUEST = 'GET_USERSBYID_DETAIL_REQUEST'
export const GET_USERSBYID_DETAIL_SUCCESS = 'GET_USERSBYID_DETAIL_SUCCESS'
export const GET_USERSBYID_DETAIL_FAILED = 'GET_USERSBYID_DETAIL_FAILED'

//User-profile
export const GET_USERSPROFILE_DETAIL_REQUEST = 'GET_USERSPROFILE_DETAIL_REQUEST'
export const GET_USERSPROFILE_DETAIL_SUCCESS = 'GET_USERSPROFILE_DETAIL_SUCCESS'
export const GET_USERSPROFILE_DETAIL_FAILED = 'GET_USERSPROFILE_DETAIL_FAILED'

export const UPDATE_USERPROFILEPASS_DETAIL_REQUEST = 'UPDATE_USERPROFILEPASS_DETAIL_REQUEST'
export const UPDATE_USERPROFILEPASS_DETAIL_SUCCESS = 'UPDATE_USERPROFILEPASS_DETAIL_SUCCESS'
export const UPDATE_USERPROFILEPASS_DETAIL_FAILED = 'UPDATE_USERPROFILEPASS_DETAIL_FAILED'

export const UPDATE_USERPROFILEDATA_DETAIL_REQUEST = 'UPDATE_USERPROFILEDATA_DETAIL_REQUEST'
export const UPDATE_USERPROFILEDATA_DETAIL_SUCCESS = 'UPDATE_USERPROFILEDATA_DETAIL_SUCCESS'
export const UPDATE_USERPROFILEDATA_DETAIL_FAILED = 'UPDATE_USERPROFILEDATA_DETAIL_FAILED'

//Permissions
export const GET_PERMISSIONS_DETAIL_REQUEST = 'GET_PERMISSIONS_DETAIL_REQUEST'
export const GET_PERMISSIONS_DETAIL_SUCCESS = 'GET_PERMISSIONS_DETAIL_SUCCESS'
export const GET_PERMISSIONS_DETAIL_FAILED = 'GET_PERMISSIONS_DETAIL_FAILED'

//pickup-routes/routes
export const GET_PICKROUTES_DETAIL_REQUEST = 'GET_PICKROUTES_DETAIL_REQUEST'
export const GET_PICKROUTES_DETAIL_SUCCESS = 'GET_PICKROUTES_DETAIL_SUCCESS'
export const GET_PICKROUTES_DETAIL_FAILED = 'GET_PICKROUTES_DETAIL_FAILED'

export const GET_ROUTEHISTORY_DETAIL_REQUEST = 'GET_ROUTEHISTORY_DETAIL_REQUEST'
export const GET_ROUTEHISTORY_DETAIL_SUCCESS = 'GET_ROUTEHISTORY_DETAIL_SUCCESS'
export const GET_ROUTEHISTORY_DETAIL_FAILED = 'GET_ROUTEHISTORY_DETAIL_FAILED'

export const ADD_PICKROUTES_DETAIL_REQUEST = 'ADD_PICKROUTES_DETAIL_REQUEST'
export const ADD_PICKROUTES_DETAIL_SUCCESS = 'ADD_PICKROUTES_DETAIL_SUCCESS'
export const ADD_PICKROUTES_DETAIL_FAILED = 'ADD_PICKROUTES_DETAIL_FAILED'

export const UPDATE_PICKROUTES_DETAIL_REQUEST = 'UPDATE_PICKROUTES_DETAIL_REQUEST'
export const UPDATE_PICKROUTES_DETAIL_SUCCESS = 'UPDATE_PICKROUTES_DETAIL_SUCCESS'
export const UPDATE_PICKROUTES_DETAIL_FAILED = 'UPDATE_PICKROUTES_DETAIL_FAILED'

export const DELETE_PICKROUTES_DETAIL_REQUEST = 'DELETE_PICKROUTES_DETAIL_REQUEST'
export const DELETE_PICKROUTES_DETAIL_SUCCESS = 'DELETE_PICKROUTES_DETAIL_SUCCESS'
export const DELETE_PICKROUTES_DETAIL_FAILED = 'DELETE_PICKROUTES_DETAIL_FAILED'
